/* Stamp app.config.json into every file that needs to know the app's name,
   version or identifier.

   There are nine of them and they are in five different languages, which is
   exactly why none of them is allowed to be the source of truth. Change
   app.config.json, run this, and the web app, the PWA manifest, the Capacitor
   config, the Xcode project and the Gradle build all agree.

   It edits rather than overwrites, so hand-written prose survives. Every edit
   is anchored to a pattern that must match: if a file has moved on and an
   anchor no longer fits, this stops and says which one rather than writing a
   half-configured app. A build that fails loudly beats a store submission with
   last month's version number on it.

   Files that do not exist yet are skipped with a note — the two native
   projects are generated by `npx cap add`, and running this before that is
   normal rather than an error. */

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const mobile = join(here, '..');
const web = join(mobile, '..');

const cfg = JSON.parse(readFileSync(join(web, 'app.config.json'), 'utf8'));

const NAME = cfg.name.sweary;
const CLEAN = cfg.name.clean;
const STORE = cfg.store.name;
const skipped = [];
const written = [];

/* ------------------------------------------------------------------ helpers */

/* Every replacement goes through here, so a stale anchor can never pass
   silently. An anchor is expected to match exactly once unless it is declared
   `many` — an Xcode project carries the bundle identifier once per build
   configuration, and that is the only legitimate reason for a repeat. Anything
   else matching twice means the file has changed shape underneath us. */
function edit(file, edits) {
  if (!existsSync(file)) { skipped.push(rel(file)); return; }
  let text = readFileSync(file, 'utf8');
  for (const [find, replace, label, many] of edits) {
    const all = new RegExp(find.source, find.flags.includes('g') ? find.flags : find.flags + 'g');
    const matches = text.match(all) || [];
    if (matches.length === 0) {
      fail(`${rel(file)}: nothing matched the anchor for ${label}\n    ${find}`);
    }
    if (matches.length > 1 && !many) {
      fail(`${rel(file)}: the anchor for ${label} matched ${matches.length} times, expected once`);
    }
    text = text.replace(many ? all : find, replace);
  }
  writeFileSync(file, text);
  written.push(rel(file));
}

function put(file, text) {
  writeFileSync(file, text);
  written.push(rel(file));
}

function rel(file) { return file.slice(web.length + 1); }

function fail(message) {
  console.error('\nconfig: ' + message + '\n');
  process.exit(1);
}

/* JSON strings and XML text are not the same thing, and a name with an
   apostrophe in it would break one of them. */
function xml(value) {
  return String(value)
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;').replace(/'/g, '&apos;');
}

/* Android string resources treat a bare apostrophe as a syntax error. */
function androidString(value) { return xml(value).replace(/'/g, "\\'"); }

/* ------------------------------------------------------------------ brand.js */

/* Written whole rather than edited: it is generated, and saying so in the file
   stops anybody editing the copy instead of the source. */
put(join(web, 'brand.js'), `/* The name, in one place.

   GENERATED FROM app.config.json — edit that and run \`npm run config\` in
   mobile/. Changing this file by hand works until the next build wipes it.

   The working name swears. That is deliberate, and it is also the single most
   likely thing to change — a shop front will not carry it — so nothing else in
   the app hardcodes it.

   The two names are not a censor and its victim: \`clean\` is a name in its own
   right rather than the sweary one with the teeth pulled. Which one shows
   follows the swearing setting, so a phone handed across the breakfast table
   does not announce itself. */

(function (root) {
  'use strict';

  root.Brand = {
    name: ${JSON.stringify(NAME)},
    clean: ${JSON.stringify(CLEAN)},

    /* What the shops call it. Only ever shown in the privacy policy and the
       About sheet's small print, where it has to match the listing. */
    store: ${JSON.stringify(STORE)},

    tagline: ${JSON.stringify(cfg.tagline)},

    version: ${JSON.stringify(cfg.version)},
    build: ${JSON.stringify(String(cfg.build))},

    pick: function (sweary) { return sweary === false ? this.clean : this.name; },

    /* For the share card, where the joke belongs to the weather rather than
       the app: a quiet signature rather than a shout. */
    signature: function (sweary) { return this.pick(sweary).toUpperCase(); }
  };

})(typeof self !== 'undefined' ? self : this);
`);

/* -------------------------------------------------------------- manifest.json */

const manifest = JSON.parse(readFileSync(join(web, 'manifest.json'), 'utf8'));
manifest.name = NAME;
manifest.short_name = NAME;
manifest.description = cfg.tagline;
manifest.background_color = cfg.colors.background;
manifest.theme_color = cfg.colors.theme;
put(join(web, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

/* ---------------------------------------------------------------- index.html */

edit(join(web, 'index.html'), [
  [/<title>[^<]*<\/title>/, `<title>${xml(NAME)}</title>`, 'the page title'],
  [/(<meta name="apple-mobile-web-app-title" content=")[^"]*(">)/,
    `$1${xml(NAME)}$2`, 'the iOS home-screen name'],
  [/(<meta name="description" content=")[^"]*(">)/,
    `$1${xml(NAME + ' — ' + cfg.tagline)}$2`, 'the page description'],
  [/(<meta name="theme-color" content=")[^"]*(">)/,
    `$1${cfg.colors.theme}$2`, 'the theme colour']
]);

/* --------------------------------------------------------- capacitor.config */

/* webDir is built by build-www.mjs. Capacitor never reads the live web app
   directly: the copy it ships has no service worker in it, because a worker
   caching a native app's own bundled files is a way to ship a phone that can
   never be updated. */
put(join(mobile, 'capacitor.config.json'), JSON.stringify({
  appId: cfg.id,
  appName: NAME,
  webDir: 'www',
  ios: {
    contentInset: 'never',
    backgroundColor: cfg.colors.background,
    limitsNavigationsToAppBoundDomains: false
  },
  android: {
    backgroundColor: cfg.colors.background,
    allowMixedContent: false
  },
  plugins: {
    SplashScreen: {
      launchShowDuration: 600,
      launchAutoHide: false,
      backgroundColor: cfg.colors.background,
      androidScaleType: 'CENTER_CROP',
      showSpinner: false,
      splashFullScreen: true,
      splashImmersive: false
    },
    StatusBar: {
      style: 'DARK',
      backgroundColor: cfg.colors.background,
      overlaysWebView: true
    },
    Keyboard: {
      resize: 'native',
      resizeOnFullScreen: true
    }
  }
}, null, 2) + '\n');

/* ------------------------------------------------------------ package.json */

const pkg = JSON.parse(readFileSync(join(mobile, 'package.json'), 'utf8'));
pkg.version = cfg.version;
put(join(mobile, 'package.json'), JSON.stringify(pkg, null, 2) + '\n');

/* -------------------------------------------------------------------- iOS */

/* CFBundleShortVersionString is the version people see; CFBundleVersion is the
   build number, which must increase with every upload or App Store Connect
   refuses it. Both come from app.config.json so they cannot drift apart. */
edit(join(mobile, 'ios/App/App/Info.plist'), [
  [/(<key>CFBundleDisplayName<\/key>\s*<string>)[^<]*(<\/string>)/,
    `$1${xml(STORE)}$2`, 'the iOS display name'],
  [/(<key>CFBundleShortVersionString<\/key>\s*<string>)[^<]*(<\/string>)/,
    `$1${cfg.version}$2`, 'the iOS version'],
  [/(<key>CFBundleVersion<\/key>\s*<string>)[^<]*(<\/string>)/,
    `$1${cfg.build}$2`, 'the iOS build number']
]);

edit(join(mobile, 'ios/App/App.xcodeproj/project.pbxproj'), [
  [/PRODUCT_BUNDLE_IDENTIFIER = [^;]+;/, `PRODUCT_BUNDLE_IDENTIFIER = ${cfg.id};`,
    'the iOS bundle identifier', true],
  [/MARKETING_VERSION = [^;]+;/, `MARKETING_VERSION = ${cfg.version};`,
    'the iOS marketing version', true],
  [/CURRENT_PROJECT_VERSION = [^;]+;/, `CURRENT_PROJECT_VERSION = ${cfg.build};`,
    'the iOS project version', true]
]);

/* ---------------------------------------------------------------- Android */

edit(join(mobile, 'android/app/src/main/res/values/strings.xml'), [
  [/(<string name="app_name">)[^<]*(<\/string>)/, `$1${androidString(STORE)}$2`,
    'the Android app name'],
  [/(<string name="title_activity_main">)[^<]*(<\/string>)/, `$1${androidString(STORE)}$2`,
    'the Android activity title'],
  [/(<string name="package_name">)[^<]*(<\/string>)/, `$1${cfg.id}$2`,
    'the Android package name'],
  [/(<string name="custom_url_scheme">)[^<]*(<\/string>)/, `$1${cfg.id}$2`,
    'the Android URL scheme']
]);

edit(join(mobile, 'android/app/build.gradle'), [
  [/applicationId "[^"]+"/, `applicationId "${cfg.id}"`, 'the Android application ID'],
  [/versionCode \d+/, `versionCode ${cfg.build}`, 'the Android version code'],
  [/versionName "[^"]+"/, `versionName "${cfg.version}"`, 'the Android version name']
]);

/* ------------------------------------------------------------------- done */

console.log(`\n${STORE === NAME ? NAME : `${NAME}  (shops: ${STORE})`}`);
console.log(`${cfg.id} · ${cfg.version} (${cfg.build})\n`);
console.log('written:');
for (const f of written) console.log('  ' + f);
if (skipped.length) {
  console.log('\nnot generated yet, skipped:');
  for (const f of skipped) console.log('  ' + f);
  console.log('  (run `npx cap add ios` / `npx cap add android` first)');
}
console.log('');
