-- Telly backend, initial schema.
--
-- Written as portable SQL: no SQLite-only column types, timestamps as ISO-8601
-- text, booleans as 0/1 integers. Moving to Postgres later is a driver change
-- and a handful of type declarations, not a redesign.

CREATE TABLE users (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  username       TEXT    NOT NULL UNIQUE COLLATE NOCASE,
  display_name   TEXT    NOT NULL DEFAULT '',
  password_hash  TEXT    NOT NULL,
  password_salt  TEXT    NOT NULL,
  password_algo  TEXT    NOT NULL DEFAULT 'scrypt',
  role           TEXT    NOT NULL DEFAULT 'user',      -- 'user' | 'admin'
  enabled        INTEGER NOT NULL DEFAULT 1,
  expires_at     TEXT,                                  -- account expiry, NULL = never
  max_devices    INTEGER NOT NULL DEFAULT 2,
  created_at     TEXT    NOT NULL,
  updated_at     TEXT    NOT NULL
);

-- A device is a client install. Sessions hang off it, so an admin can revoke
-- "the bedroom TV" without touching the account's other screens.
CREATE TABLE devices (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id      INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_key   TEXT    NOT NULL,          -- stable id generated by the client
  name         TEXT    NOT NULL DEFAULT 'Device',
  platform     TEXT    NOT NULL DEFAULT '',
  app_version  TEXT    NOT NULL DEFAULT '',
  last_seen_at TEXT,
  last_ip      TEXT,
  revoked_at   TEXT,
  created_at   TEXT    NOT NULL,
  UNIQUE (user_id, device_key)
);

-- Tokens are stored only as SHA-256 hashes: a stolen database does not hand
-- anybody a working session.
CREATE TABLE sessions (
  id                 INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id            INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id          INTEGER NOT NULL REFERENCES devices(id) ON DELETE CASCADE,
  access_hash        TEXT    NOT NULL UNIQUE,
  refresh_hash       TEXT    NOT NULL UNIQUE,
  access_expires_at  TEXT    NOT NULL,
  refresh_expires_at TEXT    NOT NULL,
  created_at         TEXT    NOT NULL,
  revoked_at         TEXT
);
CREATE INDEX idx_sessions_user ON sessions(user_id);

-- An IPTV source belongs to the operator, not to a user. Upstream credentials
-- live here and are never sent to a client.
CREATE TABLE sources (
  id             INTEGER PRIMARY KEY AUTOINCREMENT,
  name           TEXT    NOT NULL,
  kind           TEXT    NOT NULL,          -- 'm3u_url' | 'm3u_text' | 'xtream'
  url            TEXT    NOT NULL DEFAULT '',
  username       TEXT    NOT NULL DEFAULT '',
  password       TEXT    NOT NULL DEFAULT '',
  epg_url        TEXT    NOT NULL DEFAULT '',
  enabled        INTEGER NOT NULL DEFAULT 1,
  last_synced_at TEXT,
  last_error     TEXT,
  channel_count  INTEGER NOT NULL DEFAULT 0,
  created_at     TEXT    NOT NULL,
  updated_at     TEXT    NOT NULL
);

-- Which users may see which sources. Entitlement lives here.
CREATE TABLE user_sources (
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  source_id  INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  created_at TEXT    NOT NULL,
  PRIMARY KEY (user_id, source_id)
);

-- Which parts of the app a user may open: live, movies, series, guide,
-- catchup, recordings, favourites, recent, settings.
CREATE TABLE user_sections (
  user_id   INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  section   TEXT    NOT NULL,
  enabled   INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (user_id, section)
);

-- Channel metadata, cached from a source. kind separates the same shelves the
-- clients already show, so Movies and Series stop being a guess at group names.
CREATE TABLE channels (
  id           INTEGER PRIMARY KEY AUTOINCREMENT,
  source_id    INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  ext_id       TEXT    NOT NULL,           -- stable id within the source
  kind         TEXT    NOT NULL DEFAULT 'live',   -- 'live' | 'movie' | 'series'
  number       INTEGER NOT NULL DEFAULT 0,
  name         TEXT    NOT NULL,
  name_key     TEXT    NOT NULL,           -- lowercased, for search
  group_title  TEXT    NOT NULL DEFAULT 'Ungrouped',
  logo         TEXT    NOT NULL DEFAULT '',
  tvg_id       TEXT    NOT NULL DEFAULT '',
  stream_url   TEXT    NOT NULL,           -- never leaves the server
  created_at   TEXT    NOT NULL,
  UNIQUE (source_id, ext_id)
);
CREATE INDEX idx_channels_source_kind ON channels(source_id, kind);
CREATE INDEX idx_channels_group ON channels(source_id, group_title);
CREATE INDEX idx_channels_name_key ON channels(name_key);

-- Programme guide. Nothing populates this yet; the shape is here so adding an
-- XMLTV ingester later is a service, not a migration of everything else.
CREATE TABLE epg_programmes (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  source_id   INTEGER NOT NULL REFERENCES sources(id) ON DELETE CASCADE,
  tvg_id      TEXT    NOT NULL,
  starts_at   TEXT    NOT NULL,
  ends_at     TEXT    NOT NULL,
  title       TEXT    NOT NULL,
  description TEXT    NOT NULL DEFAULT '',
  UNIQUE (source_id, tvg_id, starts_at)
);
CREATE INDEX idx_epg_lookup ON epg_programmes(tvg_id, starts_at);

CREATE TABLE favourites (
  user_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel_id INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  created_at TEXT    NOT NULL,
  PRIMARY KEY (user_id, channel_id)
);

CREATE TABLE recently_watched (
  user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  channel_id  INTEGER NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
  watched_at  TEXT    NOT NULL,
  position_ms INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, channel_id)
);
CREATE INDEX idx_recent_user ON recently_watched(user_id, watched_at DESC);

CREATE TABLE user_settings (
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  key     TEXT    NOT NULL,
  value   TEXT    NOT NULL,
  PRIMARY KEY (user_id, key)
);

-- Who did what: useful the first time somebody asks why an account stopped
-- working, and the basis of the admin panel's activity view.
CREATE TABLE audit_log (
  id         INTEGER PRIMARY KEY AUTOINCREMENT,
  at         TEXT    NOT NULL,
  user_id    INTEGER,
  actor      TEXT    NOT NULL DEFAULT '',
  action     TEXT    NOT NULL,
  detail     TEXT    NOT NULL DEFAULT '',
  ip         TEXT    NOT NULL DEFAULT ''
);
CREATE INDEX idx_audit_at ON audit_log(at DESC);
